# reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 15s
  scrape_timeout: 15s
  #evaluation_interval: 15s

scrape_configs:
  - job_name: contentserver
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 127.0.0.1:9111
